name: persistent_socket
description: A socket which automatically reconnects when the connection is lost
version: 1.0.0
repository: https://github.com/point-source/persistent_socket

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
